import { BASE_URL } from '@/lib/constants'

export const projects = [
  {
    id: '1',
    title: 'Dankaab',
    description: `is a simple ecommerce mobile application. It allows users to browse products, add items to a cart, and purchase orders.`,
    image: BASE_URL + '/projects/dankaab-app.png',
    new: true,
    content: `<h1>Heading 1</h1>`,
  },
  {
    id: '2',
    title: 'Wadaag',
    description: `is all-in-one mobile app for transportation, shopping, and housing. Ride, find goods, book rentals - all in one simple app.`,
    image: BASE_URL + '/projects/wadaag-app.png',
    new: false,
    content: `<h1>Heading 1</h1>`,
  },
  {
    id: '3',
    title: 'Soomar',
    description: `is a mobile marketplace app that allows users to easily find and purchase products on-the-go.`,
    image: BASE_URL + '/projects/soomar-app.png',
    new: false,
    content: `<h1>Heading 1</h1>`,
  },
  {
    id: '4',
    title: 'Kinyozi App',
    description: `simplifies barbershop appointments, enabling personalized grooming experiences.`,
    image: BASE_URL + '/projects/kinyozi-app.png',
    new: false,
    content: `<h1>Heading 1</h1>`,
  },
  {
    id: '5',
    title: 'Sahal Book',
    description: `Comprehensive accounting software for Small and Medium Businesses.`,
    image: BASE_URL + '/projects/sahalbook.png',
    new: false,
    content: `<h1>Heading 1</h1>`,
  },
  {
    id: '6',
    title: 'Sado Somalia',
    description: `is an NGO website that empowers communities through compassionate aid and sustainable initiatives.`,
    image: BASE_URL + '/projects/sado-web.png',
    new: false,
    content: `<h1>Heading 1</h1>`,
  },
  {
    id: '7',
    title: 'TopTayo Data Recharging',
    description: `is a mobile app that allows users to recharge their data plans with a single tap offline & online.`,
    image: BASE_URL + '/projects/toptayo-app.png',
    new: true,
    content: `<h1>Heading 1</h1>`,
  },
]
