import Document, { Html, Head, Main, NextScript } from 'next/document'
import Script from 'next/script'

class MyDocument extends Document {
  static async getInitialProps(ctx: any) {
    const initialProps = await Document.getInitialProps(ctx)
    return { ...initialProps }
  }

  render() {
    return (
      <Html>
        <Head>
          <meta name='description' content='Generated by Ahmed Ibrahim Samow' />
          <link rel='icon' href='/logo.png' />
        </Head>
        <body>
          <Main />
          <NextScript />
          <noscript
            dangerouslySetInnerHTML={{
              __html: `<iframe
                      src='https://www.googletagmanager.com/ns.html?id=GTM-5C7QCDH'
                      height='0'
                      width='0'
                      style='display:none;visibility:hidden'
                    />`,
            }}
          />
        </body>
      </Html>
    )
  }
}

export default MyDocument
