import type { NextPage } from 'next'
import Head from 'next/head'
import Hero from '../components/Hero'

const Home: NextPage = () => {
  return (
    <div className=''>
      <Head>
        <title>Ahmed Ibrahim</title>
        <meta
          name='description'
          content='Generated by Ahmed Ibrahim Samow Portfolio'
        />
      </Head>
      <Hero />
    </div>
  )
}

export default Home
