import type { NextPage } from 'next'
import Head from 'next/head'
import Hero from '../components/Hero'
import Clients from '../components/Clients'

const Home: NextPage = () => {
  return (
    <div className=''>
      <Head>
        <title>Ahmed Ibrahim</title>
        <meta
          name='description'
          content='Generated by Ahmed Ibrahim Samow Portfolio'
        />
      </Head>
      <Hero />
      <div className='bg-light py-4'>
        <Clients />
      </div>
    </div>
  )
}

export default Home
