import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
const Home: NextPage = () => {
  return (
    <div className='d-flex justify-content-center align-items-center vh-100   flex-column position-relative'>
      <Head>
        <title>Ahmed Ibrahim Portfolio</title>
        <meta
          name='description'
          content='Generated by Ahmed Ibrahim Samow Portfolio'
        />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='text-center'>
        <p>This site is under development and will be updated soon.</p>
        <p>
          In an emergency <br />
          <a
            className='text-decoration-none text-info'
            href='mailto:ahmaat19@gmail.com'
          >
            📧 ahmaat19@gmail.com
          </a>
          <br />
          <a
            className='text-decoration-none text-info'
            href='tel:+252615301507'
          >
            📱 +252 (0) 61 530 1507
          </a>
        </p>
      </div>

      <Link href='/blog' className='mt-5'>
        <a className='text-decoration-none text-info'>simple blog post</a>
      </Link>

      <footer className='position-absolute bottom-0 mb-5'>
        <a
          href='https://websom.dev'
          target='_blank'
          rel='noopener noreferrer'
          className='img-fluid'
        >
          <span>
            <Image
              src='https://www.websom.dev/_next/image?url=%2Ffavicon.png&w=48&q=75'
              alt='Vercel Logo'
              width={60}
              height={60}
              className='my-auto'
            />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
